### ISSUE TITLE
2 threads?

### ISSUE THREAD

**Issue by SzotsGabor** [Orbital-Web/Raphael#1]
I have noticed that the engine uses 2 threads when on move. Why is that? Even if it is not used for calculating moves it takes away resources from other engines so it is undesirable.

Regards,
Gabor Szots
CCRL testing group

**Comment by Orbital-Web** [comment]
Hi, are you referring to the UCI engine? 
If so, I'm using one thread to get input asynchronously (so I can call stop even while the engine is thinking), and the main thread to call the engine and calculate moves. I'm not sure if this was the best way, so let me know if you have any suggestions.

The old version used to create another thread for time keeping, but I realized that was unnecessary and instead check if the time has ran out every few nodes in the newer versions (from 1.6 or 1.7 I believe).

**Comment by SzotsGabor** [comment]
I am an average user so I don't think I can give you advice on this. Anyway, all engines I know use only one thread (unless in multi-threaded mode). I think they do that by polling input.
When I run v1.7 and issue 'go infinite' I can see about 7% CPU usage (mine is a 20-thread machine). Of course that is not much but can be an issue when only a few cores are available.

BTW, in the exe name and in UCI id may you include version number, that would make it easier to avoid confusion when several versions are in use.

**Comment by Orbital-Web** [comment]
I'm not sure about the input part. I've been looking at how other open source engines do it, and it seems like all of them I've looked at so far uses threading (even Stockfish). I've also confirmed this by seeing how many threads were active when Stockfish was running. 

I also noticed my one is a little different. Instead of creating a separate thread for the engine to think and getting the input on the main thread, my code does it in reverse. Regardless, the behavior is the same, but with the load balance of each threads being different. 

The only other way I can think of doing it would require a pretty hefty restructuring of the code architecture, and I'm not sure if the gain in process would be large enough to be worthwhile. 

Nonetheless, I added the version number after the name in the id. The new build can be found in v1.7 releases page.

**Comment by SzotsGabor** [comment]
I thought I'd test it under Cute Chess but it won't install, Cute Chess saying "no response to ping". Could be related to the above problem.
Also, when run from the command line and analyzing, it fills the lines extremely slowly. BTW, it seems not to understand the 'go depth <n>' command, it does not stop at depth n.
Anyway, I'm going to test it as soon as I have a free Arena.

**Comment by Orbital-Web** [comment]
Oh yes, I am yet to implement the go depth command. I'll work on that in my spare time. 
I've also noticed the slow output, though I'm not too sure why it's doing that to be honest. It's probably related to the asynchronous input in the main thread. I'll try flipping those threads around to see if it fixes anything.

I've never tried my engine on cute chess. That's weird. It's worked fine on Lucas Chess and Arena. I'll also give it a go sometime soon.

Thanks for letting me know.

**Comment by Orbital-Web** [comment]
I fixed the slow io by making a thread and detaching it to compute the best move. That way, I don't have to use the weird trick I did to continuously get the user input. The build has been updated in the v1.7 release.

**Comment by SzotsGabor** [comment]
Yes, output speed has improved.  The "no response to ping" problem still persists.

But the main problem is that I cannot make it move under Arena. I'm going to investigate this further when I have time.

**Comment by Orbital-Web** [comment]
I think I figured out the ping thing (I was using ready instead of isready), I’ll push it once I get home. By “move under Arena”, do you mean inside Arena the chess gui? Or is that like a mode in Cute Chess. 

I had a broken build up for about an hour (before I made the previous comment). If you were using that version, it wouldn’t send the move until stop or quit was called, so it would be great if you could redownload the newest version in 1.7. 

Also, thanks a lot for testing things out. I haven’t extensively tested the UCI so it helps out a lot.

**Comment by SzotsGabor** [comment]
I have just downloaded the exe but it is the same as before. And it does not move under the Arena GUI.

**Comment by Orbital-Web** [comment]
It seems like the issue had something to do with the flushing of cout, where it would sometimes print and sometimes not print anything when thinking.

Anyways, that's fixed now, and I've also added support for `go depth n`, `go movetime t`, `go infinite`, and `go nodes n`. Infinite still stops if it finds a mate, I may look into fixing that some other time. 

As always, the new build can be found in v1.7 releases page.

**Comment by SzotsGabor** [comment]
It seems you have fixed all issues now. I'm starting a new tournament today.

EDIT: Oops, I tried it some short games (30s+0.2s) and it lost all on time because of 'connection stalls'. That was under Cute Chess. I'm afraid I can't tell more.

**Comment by SzotsGabor** [comment]
Under Arena it loses on time often, even in won positions. Must be related to the disconnect problem. I use 85s+1s time control, maybe it matters.

**Comment by Orbital-Web** [comment]
Hmm, I'll look into that. Could you hit f4 and see if there is anything weird going on with the connection of the engine? If not, I'm assuming that's a bug with my time control algorithm with increments.

**Comment by Orbital-Web** [comment]
I believe all the issues are fixed now. It was because I forgot to print out the bestmove when it finds mate after I made some changes to how the output works in uci mode.

I have also renamed the release file as `Raphael1.7` to avoid confusion in future versions. Thanks a lot for testing and notifying me of these issue, and let me know if anything new pops up!

**Comment by SzotsGabor** [comment]
Only the stall problem has remained, as far as I can tell. Under Arena results have improved significantly since I've been using the latest fix. Keep up the good work.
BTW, CCRL likes to include author's country on its lists. I guess yours is Japan, isn't it?

**Comment by Orbital-Web** [comment]
Thank you! Yup, is that passed through id in the UCI, or is it just saved externally (I didn't see any output on the author's country in the UCI outputs so)?

**Comment by SzotsGabor** [comment]
> Thank you! Yup, is that passed through id in the UCI, or is it just saved externally (I didn't see any output on the author's country in the UCI outputs so)?

It's something you tell us if you feel like it. Not obligatory, not to be included in engine id.
